[build]
  # Folder to deploy (typically for static sites)
  publish = "/" # Replace "dist" with the folder where your HTML/CSS/JS files are stored
  # Location of your Netlify Functions folder
  functions = "netlify/functions"
